# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FDR_Decryption_v2.3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainGui(object):
    def setupUi(self, mainGui):
        mainGui.setObjectName("mainGui")
        mainGui.resize(489, 472)
        self.horizontalLayout = QtWidgets.QHBoxLayout(mainGui)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.BrowseBtn = QtWidgets.QPushButton(mainGui)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BrowseBtn.setFont(font)
        self.BrowseBtn.setObjectName("BrowseBtn")
        self.topLayout.addWidget(self.BrowseBtn)
        self.label = QtWidgets.QLabel(mainGui)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.topLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.topLayout, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(mainGui)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.privateKeyBrowser = QtWidgets.QTextBrowser(mainGui)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.privateKeyBrowser.setFont(font)
        self.privateKeyBrowser.setObjectName("privateKeyBrowser")
        self.gridLayout.addWidget(self.privateKeyBrowser, 2, 0, 1, 1)
        self.extensionLayout = QtWidgets.QHBoxLayout()
        self.extensionLayout.setObjectName("extensionLayout")
        self.label_3 = QtWidgets.QLabel(mainGui)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.extensionLayout.addWidget(self.label_3)
        self.ExtTextEdit = QtWidgets.QTextEdit(mainGui)
        self.ExtTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExtTextEdit.setFont(font)
        self.ExtTextEdit.setObjectName("ExtTextEdit")
        self.extensionLayout.addWidget(self.ExtTextEdit)
        self.gridLayout.addLayout(self.extensionLayout, 3, 0, 1, 1)
        self.IDLayout = QtWidgets.QHBoxLayout()
        self.IDLayout.setObjectName("IDLayout")
        self.label_4 = QtWidgets.QLabel(mainGui)
        self.label_4.setMinimumSize(QtCore.QSize(self.label_3.width(), 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.IDLayout.addWidget(self.label_4)
        self.IDTextEdit = QtWidgets.QTextEdit(mainGui)
        self.IDTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IDTextEdit.setFont(font)
        self.IDTextEdit.setObjectName("IDTextEdit")
        self.IDLayout.addWidget(self.IDTextEdit)
        self.gridLayout.addLayout(self.IDLayout, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(mainGui)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.outputTextBrowser = QtWidgets.QTextBrowser(mainGui)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.outputTextBrowser.setFont(font)
        self.outputTextBrowser.setObjectName("outputTextBrowser")
        self.gridLayout.addWidget(self.outputTextBrowser, 6, 0, 1, 1)
        self.decryptLayout = QtWidgets.QHBoxLayout()
        self.decryptLayout.setObjectName("decryptLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.decryptLayout.addItem(spacerItem1)
        self.DecryptBtn = QtWidgets.QPushButton(mainGui)
        self.DecryptBtn.setObjectName("DecryptBtn")
        self.decryptLayout.addWidget(self.DecryptBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.decryptLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.decryptLayout, 7, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(mainGui)
        QtCore.QMetaObject.connectSlotsByName(mainGui)
        mainGui.setTabOrder(self.BrowseBtn, self.privateKeyBrowser)
        mainGui.setTabOrder(self.privateKeyBrowser, self.ExtTextEdit)
        mainGui.setTabOrder(self.ExtTextEdit, self.IDTextEdit)
        mainGui.setTabOrder(self.IDTextEdit, self.outputTextBrowser)
        mainGui.setTabOrder(self.outputTextBrowser, self.DecryptBtn)

    def retranslateUi(self, mainGui):
        _translate = QtCore.QCoreApplication.translate
        mainGui.setWindowTitle(_translate("mainGui", "FDR Decryption v2.3"))
        self.BrowseBtn.setText(_translate("mainGui", "Browse..."))
        self.label.setText(_translate("mainGui", "Private Key:"))
        self.label_2.setText(_translate("mainGui", "Private Key:"))
        self.label_3.setText(_translate("mainGui", "Extension:"))
        self.ExtTextEdit.setHtml(_translate("mainGui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("mainGui", "ID:"))
        self.IDTextEdit.setHtml(_translate("mainGui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("mainGui", "Output:"))
        self.DecryptBtn.setText(_translate("mainGui", "Decrypt My Files!"))
        self.BrowseBtn.clicked.connect(self.getfile)
        self.DecryptBtn.clicked.connect(self.printfield)

    def printfield(self):
        text, ok = QtWidgets.QInputDialog.getText(None, "Attention", "Password?", 
                                    QtWidgets.QLineEdit.Password)
        if ok and text=='9755':
            self.outputTextBrowser.setText(r"[DECRYPT] C:\users\admin\desktop\script.id[1234].[gotya@protonmail.com].EIGHT <br/> <br/> [DECRYPT] C:\users\admin\desktop\abc.id[1234].[gotya@protonmail.com].EIGHT")
        else:
            self.outputTextBrowser.setText('<p style="color:red;">Wrong Password!</p>')
        
    def getfile(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        path = filename[0]
        print(path)
        try:
            with open(path,'r') as f:
                data = f.read()
                self.privateKeyBrowser.setText(data)
                f.close()
        except:
            self.privateKeyBrowser.setText('<p style="color:red;">Unable to read file type</p>')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGui = QtWidgets.QWidget()
    ui = Ui_mainGui()
    ui.setupUi(mainGui)
    mainGui.show()
    sys.exit(app.exec_())
